# ---------------------------------------------------------------
# 基于 Deraining_Restormer.yml 修改，适配自定义多源去雨数据集
# 训练环境: 8x A100 (80GB)
# 数据集: sampled_dataset_balanced (7个去雨数据集的平衡采样)
# 训练集: ~7361 对图像 (AllRain)
# 验证集: 使用 RainDS-Syn 测试集 (267对，合成数据便于定量评估)
# ---------------------------------------------------------------

# general settings
name: Deraining_AllRain_Restormer
model_type: ImageCleanModel
scale: 1
num_gpu: 8  # 8x A100
manual_seed: 100

# dataset and data loader settings
datasets:
  train:
    name: TrainSet
    type: Dataset_PairedImage
    dataroot_gt: ./Deraining/Datasets/train/AllRain/target
    dataroot_lq: ./Deraining/Datasets/train/AllRain/input
    geometric_augs: true

    filename_tmpl: '{}'
    io_backend:
      type: disk

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 8

    ### -------------Progressive training--------------------------
    # 数据集较小(~7361)，适当减少总迭代次数
    # 原始Rain13K有13000+图像，300k迭代
    # 我们约7361图像，按比例调整为200k迭代
    mini_batch_sizes: [8,5,4,2,1,1]
    iters: [60000,44000,32000,24000,24000,16000]
    gt_size: 384   # Max patch size for progressive training
    gt_sizes: [128,160,192,256,320,384]
    ### ------------------------------------------------------------

    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: ValSet
    type: Dataset_PairedImage
    dataroot_gt: ./Deraining/Datasets/test/RainDS-Syn/target
    dataroot_lq: ./Deraining/Datasets/test/RainDS-Syn/input
    io_backend:
      type: disk

# network structures
network_g:
  type: Restormer
  inp_channels: 3
  out_channels: 3
  dim: 48
  num_blocks: [4,6,6,8]
  num_refinement_blocks: 4
  heads: [1,2,4,8]
  ffn_expansion_factor: 2.66
  bias: False
  LayerNorm_type: WithBias
  dual_pixel_task: False


# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  total_iter: 200000
  warmup_iter: -1 # no warm up
  use_grad_clip: true

  # Split 200k iterations into two cycles.
  # 1st cycle: fixed 3e-4 LR for 60k iters.
  # 2nd cycle: cosine annealing (3e-4 to 1e-6) for 140k iters.
  scheduler:
    type: CosineAnnealingRestartCyclicLR
    periods: [60000, 140000]
    restart_weights: [1,1]
    eta_mins: [0.0003,0.000001]

  mixing_augs:
    mixup: false
    mixup_beta: 1.2
    use_identity: true

  optim_g:
    type: AdamW
    lr: !!float 3e-4
    weight_decay: !!float 1e-4
    betas: [0.9, 0.999]

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1
    reduction: mean

# validation settings
val:
  window_size: 8
  val_freq: !!float 4e3
  save_img: false
  rgb2bgr: true
  use_image: true
  max_minibatch: 8

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: true

# logging settings
logger:
  print_freq: 1000
  save_checkpoint_freq: !!float 4e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
